/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dinaraparanid_prima_utils_rustlibs_NativeLibrary */

#ifndef _Included_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
#define _Included_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    artistImageBind
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_artistImageBind
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    calcTrackTime
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_calcTrackTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    playlistTitle
 * Signature: ([B[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_playlistTitle
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    newTrack
 * Signature: (J[B[B[B[BJ[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_newTrack
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackAndroidId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackAndroidId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackTitle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackTitle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackArtist
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackArtist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackPlaylist
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackPlaylist
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackPath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackPath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackRelativePath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackRelativePath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    getTrackDisplayName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_getTrackDisplayName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
