/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dinaraparanid_prima_utils_rustlibs_NativeLibrary */

#ifndef _Included_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
#define _Included_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dinaraparanid_prima_utils_rustlibs_NativeLibrary
 * Method:    artistImageBind
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinaraparanid_prima_utils_rustlibs_NativeLibrary_artistImageBind
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
